spring.application.name=exception

#server.error.whitelabel.enabled=false
spring.web.error.whitelabel.enabled=false

#server.error.include-exception=true
spring.web.error.include-exception=true

#server.error.include-message=always
spring.web.error.include-message=always

#server.error.include-stacktrace=on_param
spring.web.error.include-stacktrace=on_param

#server.error.include-binding-errors=on_param
spring.web.error.include-binding-errors=on_param
